### ISSUE TITLE
How to save README.md as a PDF

### ISSUE THREAD

**Issue by rickecon** [UC-MACSS/persp-analysis#1]
We want to be able to save the `README.md` file for the repository as a PDF. In this instance, the `README.md` is the syllabus for our Perspectives on Analysis class. My solution that worked pretty well is to do the following steps.

1. Download the [grip](https://github.com/joeyespo/grip) application. I used the [Homebrew](http://brew.sh/) package manager to install grip.
2. Navigate in terminal to the folder where your `README.md` file is. Type `grip README.md`.
3. This will render the `README.md` file as HTML on a localhost URL that you can access via your browser. In your terminal, it should tell you where it has rendered the `README.md` file, for example: `* Running on http://localhost:6419/`.
4. Paste the localhost URL into your browser.
5. Use your browser's functionality to print the page.
6. Select PDF as your printer.

This method worked pretty well (see `syllabus.pdf`) except for one strange overlap at the bottom of the first page and the top of the second page. Let me know if you find anything better.

**Comment by bensoltoff** [comment]
Done. 51fc4988ef04861f83eab8d17c74a6a5ccf74fdd

**Comment by briancarlbahr** [comment]
FYI you can just copy/paste the html from the github page to libre office writer and then export to pdf in like 10 seconds with no messing around.
