### ISSUE TITLE
Asking Questions, Questions

### ISSUE THREAD

**Issue by tamos** [UC-MACSS/persp-analysis#151]
For the Asking Questions assignment:

- To what extent would you like the project developed (i.e., general topics for questions--> draft survey?)
- Are the rules the same as the previous assignment re: reasonable assumptions of funding, etc.?
- Would the specific tools (e.g., ODK, Google Forms) be worth including?

**Comment by bensoltoff** [comment]
* Have a specific research question and specific survey questions to measure your outcome of interest and whatever key independent variables you wish to use to explain/predict that outcome
* Same rules apply
* Meh. Yes, to the extent they are important to the digital-enhancement of your survey. For example, you used Google Forms. Yay! Why choose that over something else? Convenience, or does using Google Forms allow you to do something a more traditional or other kind of digital survey does not allow you to do?

**Comment by tamos** [comment]
Can you also clarify the distinctions between enriched, enhanced, and amplified?

**Comment by bensoltoff** [comment]
"Digitally-enhanced" meaning the proposed research design is not just a basic survey, but includes a digital or computational element. A la one of the types from Bit by Bit or discussed in class this week. It could be how you ask the question(s) (e.g. ecological momentary assessment, wiki question), or how you conduct the survey (e.g. enriched asking and amplified asking designs). It doesn't need to include both. See Bit by Bit and your notes for a more detailed discussion of the differences between enriched and amplified asking.
