### ISSUE TITLE
Won't let me commit to student folder

### ISSUE THREAD

**Issue by dgamarnik** [UC-MACSS/persp-analysis#161]
For some reason when I try to commit something to my student folder (gamarnik_dan) it goes into a new "patch" instead (which I think is my forked directory of the class). It should be mapped to the master and not into the forked folder.

**Comment by dgamarnik** [comment]
Apparently when I set it to commit to the master it doesn't show up. The latest commit to the (master) student folder should be called "test"

**Comment by bensoltoff** [comment]
I'm not quite sure I understand the problem. Can you not commit your assignment 2 file to your fork? As in when you try to create the commit you get an error message?

**Comment by bensoltoff** [comment]
You might want to stop by Ryan's office hours tomorrow to troubleshoot. It sounds like it might be a problem easier solved in-person, but if you can provide a more descriptive error message I can try and help you here.

**Comment by dgamarnik** [comment]
The underlying problem is that I can't commit it the student folder. If it helps, the error message I get on GitDesktop is 

"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

The repository I set it to is (https://github.com/UC-MACSS/persp-analysis/tree/master/students/gamarnik_dan)

**Comment by bensoltoff** [comment]
But the repo you want to push to is `https://github.com/dgamarnik/persp-analysis`. Your commits are made locally, pushed to that repo (your fork), and then you open a pull request to merge the changes into the original master repository (uc-macss/persp-analysis)

**Comment by dgamarnik** [comment]
I'll do that then.
