### ISSUE TITLE
Summary of mid-course feedback

### ISSUE THREAD

**Issue by bensoltoff** [UC-MACSS/persp-analysis#212]
So a brief summary of the most frequent comments in the feedback you provided (for those interested, the response rate was approximately 50%, though I still don't know if my analysis is plagued by non-response bias):

# What has contributed to your learning in this class

## Lots of people like *Bit by Bit*

I too think it's a good summary of the major research designs and prominent research published in computational social science, though it does not serve as a replacement for reading the original research article. Several of you noted it was beneficial when I assigned an article also discussed in *Bit by Bit* as the textbook helped to summarize and clarify the major points from the article.

## The connection to your own future research projects

A few of you said it was helpful that we are relating these projects to research you may conceivably do in the next couple of years here at UChicago. That is one of the major objectives for the course, and my hope is that you do not forget all about survey and experimental designs when it comes to your own research. It is easy to find a canned package of observational data and apply some machine learning algorithms to it, but remember the Schrodt article - we don't learn a ton more by re-analysis of the same dataset. Don't forget this when you think about your research paper in the spring and your thesis next year.

# What you would like to change

## Make it an elective

No.

## Not enough application

Some of you asked when you'd be doing applied work, actually building and testing statistical models. You will be doing that next term ([see the syllabus from last year for examples of what methods we will teach you](https://github.com/UC-MACSS/persp-model)). This term focuses on research design and the process of designing a research project prior to collecting data and analyzing results.

## A lot of reading/not enough reading

Some asked for more articles to read with the different methods, while others asked for fewer articles. I am trying to strike a balance between exposing you to substantive applications of these broad methodological approaches and overloading you with reading. I already cut back from the reading load from last year. That said, the value of this course to you is what you make it. If you skip all the readings, then you will get very little out of class discussions and have nothing to contribute. If you read the articles, then you can contribute and you'll be able to better follow the discussion and contribute in small groups.

For those who want to read more articles, most of the *Bit by Bit* chapters include a table of additional articles employing the methods discussed in that chapter (I know at least this exists for the experiments chapter). I strongly encourage you to look at some of those readings if you want to dive further into a specific methodology.

### Too many political science articles

I am a political scientist, so I admit I am a bit biased by my perspective and prior exposure. That said, I went back and tabulated the frequency of articles by major discipline:

Discipline | Number of readings
----------|---------------------
Political science | 10
Sociology | 7
Statistics/other | 6
Economics | 3
Psychology | 1-ish (the conservatives/liberals are happier article)

So we could use some more econ and psych articles, and perhaps fewer poli sci articles. I'll try to balance it out more in the second half of the term.

## Class is too long/I'm hungry at noon

Why does Perspectives meet when it does? Simply put, we wanted a single time slot for the Perspectives course to meet in the fall, winter, and spring quarters. And there are a significant range of courses first-year Computation students may take, including required courses such as the CAPP programming sequence, linear algebra, statistics, etc. Computational psychology students also have a regimented sequence of courses that meet only once per term. Plus we draw a lot of certificate students from the MAPSS program which also includes some required courses. We tried to find a time that avoided conflicts with any of these requirements, which pretty much left MW at 11:30 as the only option.

We also found that an 80 minute class session was not sufficient on many days to cover the range of material we need to teach you at a sufficient depth, hence we extended it to a two-hour class. The alternative approach, which is common at UChicago, is to squeeze a semester of material (16 weeks) into 10 weeks by assigning tons of outside readings and assignments with no in-class instruction on the material. Which many students dislike, for good reason. As you've seen occasionally this term, if we finish the material early I have no problem ending class early. This is more likely to occur when students come prepared to discuss the articles and I can spend less time summarizing them. But I can only do that when the majority of students come to class prepared. [A classic question of causality.](https://en.wikipedia.org/wiki/Chicken_or_the_egg)

As for your hunger, look at it from my point of view. I teach Perspectives MW 11:30-1:20. I also teach a computing class MW 1:30-2:50. And I have a lab for that computing class W 3:00-4:20. If you're hungry during Perspectives, do what I do: eat lunch at 11. It's a bit early, so pack an afternoon snack (once you have a child of your own you'll discover the benefits of afternoon snacks).

**Comment by PhilipCaoChicago** [comment]
Haha~~  Love the idea of afternoon snacks~~ Kids are cute, but noisy sometimes
