### ISSUE TITLE
Survey paper evaluations posted on Canvas

### ISSUE THREAD

**Issue by bensoltoff** [UC-MACSS/persp-analysis#215]
Sorry for the delay in returning your scores on the last assignment. Distribution of scores compared to the first assignment:

![assign](https://user-images.githubusercontent.com/6217899/32147302-1088f86a-bcb3-11e7-997e-979198e5cc16.png)

Median score is the same as the first assignment (8.5/10) with a little wider variance this time. If you have questions about your feedback, please feel free to reach out privately to me or one of the TAs.

**Comment by PhilipCaoChicago** [comment]
It could not be a continuous density. Should looks like a step function. Maybe could title as smooth fitted curve of distribution function. 😄

**Comment by bensoltoff** [comment]
In fact it is a smooth fitted curve of the density of the distribution of assignment scores. A step function (i.e. histogram) would not be the best visual choice here because I want to preserve the ability to compare the density curve for each completed assignment. In a univariate context a histogram is a perfectly fine choice since the variable in question is continuous, but that is also the case for a density estimate such as a kernel estimator. In fact a histogram would introduce numerous barriers to interpretation across assignments since I want both densities plotted on the same graphing window. A small multiples plot could work, but in my opinion is more difficult to make direct comparisons looking back and forth between the windows. If you're more interested in density estimators and visualizations for univariate statistics, we will cover this in some detail near the end of the term. I also cover these topics in my course on [data visualization](https://github.com/uc-cfss/dataviz/).
