### ISSUE TITLE
Debt Question on PSet

### ISSUE THREAD

**Issue by gmvelez** [UC-MACSS/persp-analysis#261]
Hi,

Nora and I were having difficulty in part 3.  We are using R and trying to create a for loop in order to have it deduct from the debt.

The best that we have been able to figure out is the following, but we have two issues:

1) We are stuck in the last step of figuring out how to call the debt from the previous year (since this is a dataframe instead of a vector, we aren't sure how to do that.

2) We keep getting the following error and are not sure what the problem with our for loop is: Error in for (. in year) seq_along(id) : 4 arguments passed to 'for' which requires 3

Code:

 simulatedIncome %>%
   mutate(debt = 95000) %>%
   for(year in seq_along(id)){
     if(year == 2019) {
     debt <- (95000 - income*.1)
     } else{
       debt <- simulatedIncome$debt[year-1] - income*.1 
     } 
   }

Thanks!

**Comment by bensoltoff** [comment]
To refer to the previous row in a data frame, look at using the `lag()` function. As for the second problem, you cannot pipe directly into a `for` loop. Store

```r
simulatedIncome %>%
  mutate(debt = 95000)
```

as a separate object, then write a `for` loop that modifies that object. Remember that when piping, the first argument of the next function is always the output of the previous line. So the `for()` function is actually getting an extra argument: the data frame. Hence your error message about 4 arguments when `for()` requires 3.

**Comment by gmvelez** [comment]
That makes a lot of sense.

Thanks!
