### ISSUE TITLE
Finding Error Term

### ISSUE THREAD

**Issue by johnhenrypezzuto** [UC-MACSS/persp-analysis#264]
Hi,

How can I take the log of the error term, if the error term is sometimes negative? Should I be taking the absolute value of the error term? Or the I2 norm?

**Comment by bensoltoff** [comment]
The error term is distributed log-normally. That is, the log of the error term is normally distributed. The error term itself does not take on non-positive values. One way of doing this is drawing the log-errors from a normal distribution and plugging it into the simulation equation. Then whenever you need to present or discuss the model in terms of real-dollars, exponentiate out of the logged monetary values

**Comment by jfan3** [comment]
As a follow-up, if ln(err_t) is distributed N(0, sigma^2), why can't we just have an error term err_t2=ln(err_t) subject to N(0,sigma^2), instead of having to raise err_t to log-normal and then logging it?

**Comment by bensoltoff** [comment]
I don't follow the question. Either use a function to draw a sequence of numbers from a random distribution and plug those directly into equation 1, or draw a sequence of numbers from a random log-normal distribution, log-transform those, and plug the transformed values into equation 1. Either way, whatever values for err_t you plug into the equation should fall along the entire real number line (i.e. whatever values you plug in for err_t should contain some positive and some negative values).
