### ISSUE TITLE
Initial income?

### ISSUE THREAD

**Issue by tamos** [UC-MACSS/persp-analysis#265]
Is there a particular value we should set our initial income to? Is $1 acceptable, as it is effectively zero?

To clarify, I'm referring to income at t =  2019-1.

Edit: please disregard, I found the answer.

**Comment by bensoltoff** [comment]
Your initial income in 2019 is a function of the average initial income for your cohort and some error term. The value for that initial income parameter is given to you in parts 1 and 4
