### ISSUE TITLE
Potential Legal Issues?

### ISSUE THREAD

**Issue by xiuyuanzhang** [UC-MACSS/persp-analysis#316]
Hi, Dr. Soltoff,

While I am waiting to hear back from the Amazon review team, I looked at the tasks and saw that many of them provide some monetary reward for finishing the task. My intuition, along with  the OIA office's guidelines, is telling me that it is illegal for international students with F-1 visa to accept those tasks. By receiving any monetary compensation for their work from off-campus unauthorized sources, international students would be violating the specific government regulations that come attached to our F-1 status. 

It is completely sensible to choose only tasks with zero compensation (since this is a homework assignment anyway), that's not the problem for me. I simply want to make sure that my understanding of the situation is correct. If so, perhaps you could let other international students know about this caveat. If it's not a problem at all, I would like to know the evidence supporting such a statement, namely, receiving financial compensation from employers at MTurk is legal for students with F-1 status.

Thanks!

Edit:
Here are some links to MTurk that seem to suggest Chinese citizens (from the mainland China), at least, are not legally allowed to register to become a turker. 
[MTurk is now available for Requesters in 10 more countries](https://blog.mturk.com/mturk-is-now-available-for-requesters-in-10-more-countries-a4e1fd173f0b)
[FAQs](https://requester.mturk.com/help/faq#tax_collect_non_us_workers)

**Comment by PhilipCaoChicago** [comment]
That is true. This original question is very sensitive I guess.

**Comment by ruixue-li** [comment]
I've heard that unpaid work and volunteering work are also different. So it's a really dangerous area....

**Comment by bensoltoff** [comment]
If you're worried, just do the alternative task
