### ISSUE TITLE
Does MTurk Explicitly Say How Long You Worked For?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [UC-MACSS/persp-analysis#318]
The qualifications pages seems like it shows the number of studies I participated in, but I'm not sure if it includes the length

**Comment by bensoltoff** [comment]
Each HIT should have an approximate time to complete when you sign up for the HIT and you can track for yourself if you spend at least an hour completing the work. It may not be printed on the qualifications page. By submitting the verification, we assume you completed 1 hour of work on MTurk.
