### ISSUE TITLE
Can we use jupyter notebook for Kaggle dataset plotting?

### ISSUE THREAD

**Issue by Fangfangwan** [UC-MACSS/persp-analysis#322]
as titled

**Comment by bensoltoff** [comment]
Yes

On Nov 11, 2017 5:45 PM, "Fangfangwan" <notifications@github.com> wrote:

as titled

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UC-MACSS/persp-analysis/issues/322>, or mute the thread
