### ISSUE TITLE
Can I Make a Pie Chart For My Kaggle Plot?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [UC-MACSS/persp-analysis#325]
I would like to use a pie chart for my Kaggle plot. I know there is some controversy about pie charts in the world of data visualizations, and that pie charts do not have have axises that I can label.

Can I still score full points on my data visualization by creating a pie chart? I think it would be the best visualization for data I have in mind.

**Comment by bensoltoff** [comment]
You can. Keep in mind if you use R and `ggplot2` to visualize the data, you'll have a tough time creating a pie chart - Hadley specifically dislikes pie charts for viz purposes
