### ISSUE TITLE
R Markdown as Submission?

### ISSUE THREAD

**Issue by gmvelez** [UC-MACSS/persp-analysis#331]
I just wanted to check that it would be okay to submit my assignment as an html from an R markdown document with the R script and the photos of the MTurk pages.

Thanks!

**Comment by bensoltoff** [comment]
R Markdown - yes. However make sure to use the `output: github_document` option so the final result is a `.md` file in the repo. This can be viewed directly on GitHub. Easy way to check: if you open the file on GitHub and cannot see everything we expect to see in the assignment, then it has not been submitted correctly

**Comment by gmvelez** [comment]
Thanks - makes sense!
