### ISSUE TITLE
Standardizing in PCA

### ISSUE THREAD

**Issue by gmvelez** [UC-MACSS/persp-analysis#471]
I was just wondering if we should standardized when we do the PCA analysis.  I noticed that you can do this by setting center and scale. to TRUE.

**Comment by bensoltoff** [comment]
You can, but do not do that for the assignment. The last question in part 2 addresses the issue of scaling with clustering. I think ISLR discusses the role of standardizing variables in relation to PCA. In general, it's less of an issue for PCA than for clustering methods

**Comment by gmvelez** [comment]
Thank you!
