### ISSUE TITLE
How many points is the final exam worth for?

### ISSUE THREAD

**Issue by Fangfangwan** [UC-MACSS/persp-analysis#515]
On the syllabus it says that the final exam is worth 20 points in total. However, the questions worth 3 + 4 + 3 + 3 = 13 points in total. So how does the grading work? I just want to make sure that I don't miss out any questions.
Thank you!

**Comment by bensoltoff** [comment]
Re-read the instructions for the first part. 3 points for summarizing article one + 3 points for summarizing article two + 4 points for analyzing article one + 4 points for analyzing article 2.
