### ISSUE TITLE
Petition to enroll in MACS 30000 (for non-Computation students only)

### ISSUE THREAD

**Issue by bensoltoff** [UC-MACSS/persp-analysis#62]
[Here is the petition to enroll in MACS 30000](https://goo.gl/forms/89CHuch2eR2Dc0Bp1). All students who are not part of the MA in Computational Social Science (MACSS) program need to complete this petition.

If you are a Computation student (member of MACSS) and have not yet registered for the course, contact Brett Baker to be added and tell him you have my consent to enroll.

**Comment by HyunkuKwon** [comment]
Name: Hyunku Kwon
Student ID: 12177090
Department: MAPSS

Hi, I am Hyunku Kwon, a graduate student at MAPSS. My research interests include political polarization, public opinion and computational methods, with a particular focus on American politics.
 
My current research has focused on the causal mechanisms of political polarization. Using ANES data (1992-2012), my findings reveal the process of how ideological belief system (i.e. constraint) undermines generalized trust and encourages us-against-them mentality at the individual level via regression modeling. Building on this research, my future studies will further examine the impact of polarization in the mass public on socio-political process, including (1) how mass polarization structures social movement dynamics and electoral politics; and (2) how political polarization spills over into social dimensions.

I believe computational social science courses would be extremely helpful in this research project. With Machine Learning and Text Analysis Methods (Bonikowski and Gidron 2016), I would investigate the styles and rhetoric of political discourses in electoral politics. Relational Class Analysis deployed by Baldassarri and Goldberg (2014) would help me research the macro-level ideational structure of mass public. From Jung, Soule, and King (2015) and Ghaziani and Baldassarri (2015), I would be able to understand the ideational linkages of social movements. Combined together, those computational methodologies would help me uncover the ideational dynamics between mass public, social movements, and elections. Also, drawing on Della Posta, Shi Yongren, and Michael Macy (2015), and Feng Shi, Yongren Shi, Fedor, James Evans, and Michael Macy (2017), I would understand the relation between political polarization and socio-cultural dimensions.

Seen in this light, Computational Social Sciences would be extremely helpful in developing my research project: I could interact with, build relationships with, and gain insights from computational social scientists; I could develop my nascent interest in computations; also, the courses and Certificate would definitely signal my research interests, which would help me get into Ph.D. programs with similar research projects. I thus believe this would be a great opportunity to me. Thank you for your time.

**Comment by bensoltoff** [comment]
Hi Hyunku! Please make sure to submit your petition through the link in my first post (it will send you to a Google Form where you can submit your request).
