### ISSUE TITLE
Questions re: Assignment 1

### ISSUE THREAD

**Issue by tamos** [UC-MACSS/persp-analysis#78]
* Should we be doing a literature review? If yes, to what extent?
* Can you elaborate a bit on the following point? (Beyond what is in the instructions)
    * Are we justifying its use over other methods?

"A justification for how your proposed research design takes advantage of specific methods for observational study versus alternative observational methods"

* Does this have to be a research project we are capable of doing? I.e., Can we suppose certain enabling factors (funding, access to data, time).

**Comment by bensoltoff** [comment]
* No literature review is necessary - simply state the research question in sufficient detail to complete the assignment. A few sentences of background or justification for asking the question may be helpful but I don't expect an extensive list of cited works
* As we will discuss next week, there are many different types of observational studies (e.g. counting things, measuring things, forecasting, quasi-experiments). For the assignment you will need to focus one of these types (or a related method not discussed in class) and explain why it is the best approach in designing an observational study to answer your question
* You can assume certain enabling factors, to a point. For instance, Salganik mentions inaccessibility as a negative characteristic of big data. So if your study relies on a massive study of Facebook posts, you need Facebook to grant you access. Why would they do that? Attempt to justify why they would care about your research.

We will discuss the instructions more next Wednesday.
