### ISSUE TITLE
Adding a Number Column to the Course Schedule?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [UC-MACSS/persp-analysis#92]
Would be possible to add the class number to the course schedule? Right now the course schedule has the date, and the reading schedule has the class number, but it is a little bit tricky to see how they relate together.

I think adding a class number column would make it much easier to see which readings correspond each class.

**Comment by bensoltoff** [comment]
I'm not at a computer now but sure. If you know markdown feel free to add the column yourself and open a pull request

**Comment by johnhenrypezzuto** [comment]
I've edited the markdown, it's included as part of my pull request
